const {
  emailRegexp,
  nameRegexp,
  MAX_AGE,
  MIN_AGE,
  MAX_HEIGHT,
  MIN_HEIGHT,
  MAX_WEIGHT,
  MIN_WEIGHT,
  MAX_CALORIES,
  MIN_CALORIES,
  LIMIT_JSON,
  LIMIT_FORM,
  MIN_BLOOD_TYPE,
  MAX_BLOOD_TYPE,
  LIMITIER_TIME,
  LIMITIER_COUNT,
  PUBLIC_DIR,
  HttpStatusCode,
  Role,
} = require('./constants');
const connectDB = require('./db');

module.exports = {
  emailRegexp,
  nameRegexp,
  MAX_AGE,
  MIN_AGE,
  MAX_HEIGHT,
  MIN_HEIGHT,
  MAX_WEIGHT,
  MIN_WEIGHT,
  MAX_CALORIES,
  MIN_CALORIES,
  LIMIT_JSON,
  LIMIT_FORM,
  LIMITIER_TIME,
  LIMITIER_COUNT,
  MIN_BLOOD_TYPE,
  MAX_BLOOD_TYPE,
  PUBLIC_DIR,
  HttpStatusCode,
  Role,
  connectDB,
};
